### ISSUE TITLE
Request for Spark! Tech Resources for BU Meetup

### ISSUE THREAD

**Issue by aycasolmaz** [BU-Spark/se-bu-meetup#1]
aycaslmz@bu.edu gzheng@bu.edu yjasmine@bu.edu

This is for the CS519 Project for team BU Meetup. We need an AWS NOSQL database: https://aws.amazon.com/dynamodb/?p=ft&c=db&z=3 We plan to implement a NOSQL database in order to trigger cloud functions and store the updated information in order to generate automated text messages to users using the Twilio Chatbot. This is the first feature we want to implement for now.

**Comment by IanSaucy** [comment]
Do you still plan on having the data sourced from the google form?

**Comment by IanSaucy** [comment]
@aycasolmaz bump

**Comment by gzheng0214** [comment]
@IanSaucy We would like access to DynamoDB for our NoSQL database and Lambda/Gateway to create a RESTful api to interact with it. Currently the idea is to have the data from the google form responses be stored into the NoSQL database instead of google sheets and then when we do the matching/complete match we would then update the database as well.

**Comment by IanSaucy** [comment]
Gotcha okay, I can start getting these setup. Are you married to using AWS? It's easier for me to give you access to Google Clout Platform(GCP) but I can still do AWS.

If the google form is just going to dump into DynamoDB then maybe you could build the form with this: https://retool.com/ -- We're using it for some internal tools. It will allow you to build a form that dumps right into DynamoDB

**Comment by IanSaucy** [comment]
Have you looked to see if Firebase could interface with Twillio? Would remove the need for writing your own API.

**Comment by gzheng0214** [comment]
> Gotcha okay, I can start getting these setup. Are you married to using AWS? It's easier for me to give you access to Google Clout Platform(GCP) but I can still do AWS.
> 
> If the google form is just going to dump into DynamoDB then maybe you could build the form with this: https://retool.com/ -- We're using it for some internal tools. It will allow you to build a form that dumps right into DynamoDB

We're not really tied to one cloud platform, but I think as a group we're more comfortable with AWS. And I looked into retool, but I don't know if it can provide the same flow as the google form the client gave us, since the google form conditionally displays questions based on what questions user answered beforehand and I think more users are comfortable with using google form.

**Comment by gzheng0214** [comment]
> Have you looked to see if Firebase could interface with Twillio? Would remove the need for writing your own API.

I looked into the firebase extensions (https://www.twilio.com/docs/labs/firebase-extensions), but I don't think it provides us the necessary integrations. We want to be able to update a property based on a user response, and looking through the extensions there doesn't seem to be one that allows us to do that. I think we're going to have a UI in the future to allow the client to trigger his current workflow, so we're going to have to write the API anyways.

**Comment by IanSaucy** [comment]
Right but if you plan on using Lambda + Gateway to write an API you can probably also do it with firebase functions. They are both serverless functions anyways. 

Unless there is a technology reason, I'd prefer to use either GCP(Google Cloud Platform) or Azure. They're much easier to admin from my side of things and will make it easier for yall to work as well. Which one of those would you prefer?

**Comment by minghuiyang1998** [comment]
Hello, actually  I will recommend that PM can apply for an AWS account, AWS has a free credit, and for million usage is not charged which is more than enough for this project. Then give us the account and password. Then we can develop with that account. It's not complicated. There is no extra cost.

**Comment by minghuiyang1998** [comment]
All we need is a public account belong to the project that is not owned by any member of the team.

**Comment by IanSaucy** [comment]
Unfortunately, our policy is that all hosted services need to be on our accounts

**Comment by minghuiyang1998** [comment]
yes, I know that. You apply a AWS account for us. It's still your account which is what I mean a public account belong to the project that is not owned by any member of the team. That's why we are waiting for this process.

**Comment by minghuiyang1998** [comment]
Then we can use this account for development, all the processes are the same.

**Comment by minghuiyang1998** [comment]
Because you said before that we could apply for AWS resources, we have designed and updated the architecture according to AWS in the document. Now to change the cloud service, we need to spend more time to do the same architecture design. The components of each cloud service are different, so we need to spend a lot of time. Applying for an account is a very simple process. I wish we had more time for our feature development.

**Comment by IanSaucy** [comment]
Do you have your architecture written down somewhere so that I can take a look at it?

**Comment by gzheng0214** [comment]
> Right but if you plan on using Lambda + Gateway to write an API you can probably also do it with firebase functions. They are both serverless functions anyways.
> 
> Unless there is a technology reason, I'd prefer to use either GCP(Google Cloud Platform) or Azure. They're much easier to admin from my side of things and will make it easier for yall to work as well. Which one of those would you prefer?

The reason we asked for AWS is because we're more familiar with that cloud provider so it would reduce our development time. Although you're right that any cloud provider would work, we're not used to GCP/Azure so it'll take more time to read through documentations and understand how to set up it's services.

I think what Minghui is saying is that you can create a free AWS account with the Spark account, and since our load isn't a lot, we don't need any credit to run the services so it's just signing up for an account with the Spark email (I can't sign up with mine cause mine's permanently suspended haha).

But ultimately if AWS account isn't possible, then I think we're more comfortable with Azure over GCP since some of us used it for assignment 4. 

@minghuiyang1998 @aycasolmaz If you guys have any opinions/thoughts, feel free to comment.

**Comment by gzheng0214** [comment]
> Do you have your architecture written down somewhere so that I can take a look at it?

The architecture diagram is in the database schema doc - https://docs.google.com/document/d/1hs-NumD0QCqlHZdw_pLJ_k-TDHMnFA2HPqziSQUC5Dg/edit?usp=sharing

**Comment by minghuiyang1998** [comment]
Besides, Since there will be a part connected to Twillio, using AWS can reserve an opportunity for us to use AWS SQS for scalable purposes.Instead of going through every Twillio request right away, we could just guarantee eventual consistency with SQS. if time permits, we can do that. So in fact, in order to ensure deliverable, we need to start development as soon as possible, and opening an account is the fastest and simplest way. Otherwise, we have to go back to design with GCP/Azure components.

**Comment by IanSaucy** [comment]
I'm waiting on the account setup to complete but should have something for you all in a few hours

**Comment by gzheng0214** [comment]
@IanSaucy Any updates? We are blocked in actual development until we have this (we can write pseudocode but might not work haha).

**Comment by IanSaucy** [comment]
I'm still waiting on the account to activate. Hopefully sometime today as they said 24 hours.
